

#  Properties file for all files in this folder and below
#
#  The [database] section is required.
#
#  Ps, anything after the equals sign is added to the key
#  value.
#


[database]
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5433
DATABASE_NAME=geospatial_test
DATABASE_USER=yugabyte
DATABASE_PASSWORD=




